<Type Name="FaultCallback" FullName="System.Activities.FaultCallback">
  <Metadata>
    <Meta Name="ms.openlocfilehash" Value="3b9968c74f3321146ac75a2163f5818646232cd7" />
    <Meta Name="ms.sourcegitcommit" Value="d31dc2ede16f6f7bc64e90d9f897ff54c4e3869b" />
    <Meta Name="ms.translationtype" Value="HT" />
    <Meta Name="ms.contentlocale" Value="de-DE" />
    <Meta Name="ms.lasthandoff" Value="04/03/2018" />
    <Meta Name="ms.locfileid" Value="30355834" />
  </Metadata>
  <TypeSignature Language="C#" Value="public delegate void FaultCallback(NativeActivityFaultContext faultContext, Exception propagatedException, ActivityInstance propagatedFrom);" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi sealed FaultCallback extends System.MulticastDelegate" />
  <TypeSignature Language="DocId" Value="T:System.Activities.FaultCallback" />
  <TypeSignature Language="VB.NET" Value="Public Delegate Sub FaultCallback(faultContext As NativeActivityFaultContext, propagatedException As Exception, propagatedFrom As ActivityInstance)" />
  <TypeSignature Language="C++ CLI" Value="public delegate void FaultCallback(NativeActivityFaultContext ^ faultContext, Exception ^ propagatedException, ActivityInstance ^ propagatedFrom);" />
  <AssemblyInfo>
    <AssemblyName>System.Activities</AssemblyName>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.Delegate</BaseTypeName>
  </Base>
  <Parameters>
    <Parameter Name="faultContext" Type="System.Activities.NativeActivityFaultContext" />
    <Parameter Name="propagatedException" Type="System.Exception" />
    <Parameter Name="propagatedFrom" Type="System.Activities.ActivityInstance" />
  </Parameters>
  <ReturnValue>
    <ReturnType>System.Void</ReturnType>
  </ReturnValue>
  <Docs>
    <param name="faultContext">Der für das Überprüfen des Workflowfehlers angegebene <see cref="T:System.Activities.ActivityFaultContext" />.</param>
    <param name="propagatedException">Die Ausnahme, die den Fehler verursacht hat.</param>
    <param name="propagatedFrom">Die Aktivität, die die Ausnahme ausgelöst und den Fehler generiert hat.</param>
    <summary>Stellt die Methode dar, die aufgerufen wird, wenn eine geplante Aktivität oder eines ihrer untergeordneten Elemente den Status <see cref="F:System.Activities.ActivityInstanceState.Faulted" /> annimmt.</summary>
    <remarks>To be added.</remarks>
  </Docs>
</Type>