<Type Name="FirstChanceExceptionEventArgs" FullName="System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs">
  <Metadata><Meta Name="ms.openlocfilehash" Value="5d9a578701bc3eb4e43e1042c5590eab84e26419" /><Meta Name="ms.sourcegitcommit" Value="0ec122ee5f3681159b8460ab15b409fd6e3d3ae0" /><Meta Name="ms.translationtype" Value="MT" /><Meta Name="ms.contentlocale" Value="de-DE" /><Meta Name="ms.lasthandoff" Value="10/04/2018" /><Meta Name="ms.locfileid" Value="48710780" /></Metadata><TypeSignature Language="C#" Value="public class FirstChanceExceptionEventArgs : EventArgs" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi beforefieldinit FirstChanceExceptionEventArgs extends System.EventArgs" />
  <TypeSignature Language="DocId" Value="T:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs" />
  <TypeSignature Language="VB.NET" Value="Public Class FirstChanceExceptionEventArgs&#xA;Inherits EventArgs" />
  <TypeSignature Language="C++ CLI" Value="public ref class FirstChanceExceptionEventArgs : EventArgs" />
  <TypeSignature Language="F#" Value="type FirstChanceExceptionEventArgs = class&#xA;    inherit EventArgs" />
  <AssemblyInfo>
    <AssemblyName>mscorlib</AssemblyName>
    <AssemblyVersion>2.0.5.0</AssemblyVersion>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <AssemblyInfo>
    <AssemblyName>netstandard</AssemblyName>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <AssemblyInfo>
    <AssemblyName>System.Runtime</AssemblyName>
    <AssemblyVersion>4.2.0.0</AssemblyVersion>
    <AssemblyVersion>4.2.1.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.EventArgs</BaseTypeName>
  </Base>
  <Interfaces />
  <Docs>
    <summary><span data-ttu-id="d48c8-101">Stellt Daten für das Benachrichtigungsereignis bereit, das beim erstmaligen Auftreten einer verwalteten Ausnahme ausgelöst wird, bevor die Common Language Runtime beginnt, nach Ereignishandlern zu suchen.</span><span class="sxs-lookup"><span data-stu-id="d48c8-101">Provides data for the notification event that is raised when a managed exception first occurs, before the common language runtime begins searching for event handlers.</span></span></summary>
    <remarks>
      <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="d48c8-102">Diese Klasse stellt die Ausnahmehandler für die <xref:System.AppDomain.FirstChanceException?displayProperty=nameWithType> -Ereignis mit Zugriff auf die Ausnahme.</span><span class="sxs-lookup"><span data-stu-id="d48c8-102">This class provides the exception handler for the <xref:System.AppDomain.FirstChanceException?displayProperty=nameWithType> event with access to the exception.</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="d48c8-103">Das folgende Beispiel erstellt eine Reihe von Anwendungsdomänen, die mit dem Namen `Child_0` über `Child_3`, mit einem `Worker` Objekt in jeder Anwendungsdomäne.</span><span class="sxs-lookup"><span data-stu-id="d48c8-103">The following example creates a series of application domains named `Child_0` through `Child_3`, with a `Worker` object in each application domain.</span></span> <span data-ttu-id="d48c8-104">Jede `Worker` enthält einen Verweis auf die `Worker` Objekt in der nächsten Anwendungsdomäne, mit Ausnahme der `Worker` in der letzten Anwendungsdomäne.</span><span class="sxs-lookup"><span data-stu-id="d48c8-104">Each `Worker` object has a reference to the `Worker` object in the next application domain, except for the `Worker` in the last application domain.</span></span> <span data-ttu-id="d48c8-105">Die <xref:System.AppDomain.FirstChanceException> Ereignis erfolgt in allen Anwendungsdomänen außer `Child_1`.</span><span class="sxs-lookup"><span data-stu-id="d48c8-105">The <xref:System.AppDomain.FirstChanceException> event is handled in all application domains except `Child_1`.</span></span>  
  
 <span data-ttu-id="d48c8-106">Wenn die Anwendungsdomänen erstellt wurden, ruft die Standardanwendungsdomäne die `TestException` -Methode für die erste untergeordnete Anwendungsdomäne.</span><span class="sxs-lookup"><span data-stu-id="d48c8-106">When the application domains have been created, the default application domain calls the `TestException` method for the first child application domain.</span></span> <span data-ttu-id="d48c8-107">Jede `Worker` -Objekt ruft die `TestException` -Methode für den nächsten, bis die letzte `Worker` löst eine Ausnahme, die verarbeitet oder nicht behandelt wird.</span><span class="sxs-lookup"><span data-stu-id="d48c8-107">Each `Worker` object calls the `TestException` method for the next, until the last `Worker` throws an exception that is either handled or unhandled.</span></span> <span data-ttu-id="d48c8-108">Daher alle Anwendungsdomänen, der aktuelle Thread durchläuft und `TestException` an den Stapel in jeder Anwendungsdomäne hinzugefügt wird.</span><span class="sxs-lookup"><span data-stu-id="d48c8-108">Thus, the current thread passes through all the application domains, and `TestException` is added to the stack in each application domain.</span></span>  
  
 <span data-ttu-id="d48c8-109">Wenn die letzte `Worker` Objekt verarbeitet die Ausnahme, die <xref:System.AppDomain.FirstChanceException> Ereignis wird nur in der letzten Anwendungsdomäne ausgelöst.</span><span class="sxs-lookup"><span data-stu-id="d48c8-109">When the last `Worker` object handles the exception, the <xref:System.AppDomain.FirstChanceException> event is raised only in the last application domain.</span></span> <span data-ttu-id="d48c8-110">Die anderen Anwendungsdomänen bekommen nicht die Gelegenheit zur Behandlung von Ausnahmen, damit das Ereignis nicht ausgelöst wird.</span><span class="sxs-lookup"><span data-stu-id="d48c8-110">The other application domains never get a chance to handle the exception, so the event is not raised.</span></span>  
  
 <span data-ttu-id="d48c8-111">Bei der letzten `Worker` Objekt behandelt nicht die Ausnahme, die <xref:System.AppDomain.FirstChanceException> Ereignis wird ausgelöst, in jeder Anwendungsdomäne, die einen Ereignishandler.</span><span class="sxs-lookup"><span data-stu-id="d48c8-111">When the last `Worker` object does not handle the exception, the <xref:System.AppDomain.FirstChanceException> event is raised in each application domain that has an event handler.</span></span> <span data-ttu-id="d48c8-112">Nach Abschluss der einzelnen Ereignishandler wird der Stapel entladen, bis die Ausnahme, die von der Standardanwendungsdomäne abgefangen wird fortgesetzt.</span><span class="sxs-lookup"><span data-stu-id="d48c8-112">After each event handler has finished, the stack continues to unwind until the exception is caught by the default application domain.</span></span>  
  
> [!NOTE]
>  <span data-ttu-id="d48c8-113">Ändern, um anzuzeigen, wie die Anzeige der Stapel wächst durch das das Ereignis ausgelöst wird, das näher und Annäherung an die Standardanwendungsdomäne, `e.Exception.Message` zu `e.Exception` in die `FirstChanceHandler` -Ereignishandler.</span><span class="sxs-lookup"><span data-stu-id="d48c8-113">To see how the stack display grows as the event is raised closer and closer to the default application domain, change `e.Exception.Message` to `e.Exception` in the `FirstChanceHandler` event handlers.</span></span> <span data-ttu-id="d48c8-114">Beachten Sie, dass bei `TestException` heißt über Anwendungsdomänen hinweg, es wird zweimal angezeigt: einmal für den Proxy und einmal für den Stub.</span><span class="sxs-lookup"><span data-stu-id="d48c8-114">Notice that when `TestException` is called across application domain boundaries, it appears twice: once for the proxy and once for the stub.</span></span>  
  
 [!code-csharp[System.AppDomain.FirstChanceException#1](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.appdomain.firstchanceexception/cs/example.cs#1)]
 [!code-vb[System.AppDomain.FirstChanceException#1](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.appdomain.firstchanceexception/vb/example.vb#1)]  
  
 ]]></format>
    </remarks>
    <altmember cref="E:System.AppDomain.FirstChanceException" />
  </Docs>
  <Members>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public FirstChanceExceptionEventArgs (Exception exception);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(class System.Exception exception) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.#ctor(System.Exception)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; FirstChanceExceptionEventArgs(Exception ^ exception);" />
      <MemberSignature Language="F#" Value="new System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs : Exception -&gt; System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs" Usage="new System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs exception" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="exception" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="exception"><span data-ttu-id="d48c8-115">Die Ausnahme, die gerade von verwaltetem Code ausgelöst wurde und die vom <see cref="E:System.AppDomain.UnhandledException" />-Ereignis untersucht wird.</span><span class="sxs-lookup"><span data-stu-id="d48c8-115">The exception that was just thrown by managed code, and that will be examined by the <see cref="E:System.AppDomain.UnhandledException" /> event.</span></span></param>
        <summary><span data-ttu-id="d48c8-116">Initialisiert eine neue Instanz der <see cref="T:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs" />-Klasse mit einer angegebenen Ausnahme.</span><span class="sxs-lookup"><span data-stu-id="d48c8-116">Initializes a new instance of the <see cref="T:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs" /> class with a specified exception.</span></span></summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="d48c8-117">Dieser Konstruktor wird von der common Language Runtime, durch den Anwendungscode nicht aufgerufen.</span><span class="sxs-lookup"><span data-stu-id="d48c8-117">This constructor is called by the common language runtime, not by application code.</span></span>  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName="Exception">
      <MemberSignature Language="C#" Value="public Exception Exception { get; }" />
      <MemberSignature Language="ILAsm" Value=".property instance class System.Exception Exception" />
      <MemberSignature Language="DocId" Value="P:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.Exception" />
      <MemberSignature Language="VB.NET" Value="Public ReadOnly Property Exception As Exception" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; property Exception ^ Exception { Exception ^ get(); };" />
      <MemberSignature Language="F#" Value="member this.Exception : Exception" Usage="System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.Exception" />
      <MemberType>Property</MemberType>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <Attributes>
        <Attribute FrameworkAlternate="netframework-4.0;netframework-4.5;netframework-4.5.1;netframework-4.5.2;netframework-4.6;netframework-4.6.1;netframework-4.6.2;netframework-4.7;netframework-4.7.1;netframework-4.7.2;xamarinandroid-7.1;xamarinios-10.8;xamarinmac-3.0;netframework-4.8">
          <AttributeName>get: System.Runtime.ConstrainedExecution.ReliabilityContract(System.Runtime.ConstrainedExecution.Consistency.WillNotCorruptState, System.Runtime.ConstrainedExecution.Cer.Success)</AttributeName>
        </Attribute>
      </Attributes>
      <ReturnValue>
        <ReturnType>System.Exception</ReturnType>
      </ReturnValue>
      <Docs>
        <summary><span data-ttu-id="d48c8-118">Das verwaltete Ausnahmeobjekt, das der ausgelösten Ausnahme in verwaltetem Code entspricht.</span><span class="sxs-lookup"><span data-stu-id="d48c8-118">The managed exception object that corresponds to the exception thrown in managed code.</span></span></summary>
        <value><span data-ttu-id="d48c8-119">Die gerade ausgelöste Ausnahme.</span><span class="sxs-lookup"><span data-stu-id="d48c8-119">The newly thrown exception.</span></span></value>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="d48c8-120">Die Methode, verarbeitet die <xref:System.AppDomain.UnhandledException?displayProperty=nameWithType> Ereignis untersuchen Sie die Ausnahme und entsprechende Protokollierung oder andere Notification Services ausgeführt werden kann.</span><span class="sxs-lookup"><span data-stu-id="d48c8-120">The method that handles the <xref:System.AppDomain.UnhandledException?displayProperty=nameWithType> event can examine the exception and perform appropriate logging or other notification services.</span></span>  
  
 <span data-ttu-id="d48c8-121">Beispielcode finden Sie unter <xref:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs>.</span><span class="sxs-lookup"><span data-stu-id="d48c8-121">For example code, see <xref:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs>.</span></span>  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
  </Members>
</Type>